---
title: "Draft R Markdown document"
author: "Your Name"
format: html
---

```{r setup}
library(tidyverse)
library(fs)
library(here)
source(here("R/functions.R"))
options(dplyr.summarise.inform = FALSE)
```

```{r}
user_info_df <- import_multiple_files(
  "user_info.csv",
  import_user_info
)
saliva_df <- import_multiple_files(
  "saliva.csv",
  import_saliva
)

user_info_df %>%
  select(where(is.numeric))
user_info_df %>%
  select(where(is.character))

names(list(average = mean))

saliva_df %>%
  summarise(
    across(
      c(where(is.numeric)),
      list(average = mean, sd = sd) # add the suffix "average" to the col names
    )
  )
```

```{r}
rr_df <- import_multiple_files("RR.csv", import_rr)
summarised_rr_df <- rr_df %>%
  group_by(file_path_id, day) %>%
  summarise(across(ibi_s, list(
    mean = ~ mean(.x, na.rm = TRUE), # and not mean alone so the treatment of missing value can be precised
    sd = ~ sd(.x, na.rm = TRUE)
  ))) %>%
  ungroup() # to remove some metadata in the code to avoid issues in further wrangling
```

## Exercise: Summarise  Actigraph

```{r}
actigraph_df <- import_multiple_files("Actigraph.csv", import_actigraph)
summarised_actigraph_df <- actigraph_df %>%
  group_by(file_path_id, day) %>%
  summarise(across(hr, list(
    mean = ~ mean(.x, na.rm = TRUE),
    sd = ~ sd(.x, na.rm = TRUE)
  ))) %>%
  ungroup()
```
